### ISSUE TITLE
Fixing useState setup

### ISSUE THREAD

**Issue by TauqeerAhmad5201** [TauqeerAhmad5201/react-basic-push#6]
Solve the setup of useState setup in `usestate` branch. 

The function contains the basic initialization of useState. 

Checkout in [src/components/TellUs.js](https://github.com/TauqeerAhmad5201/react-basic-push/blob/usestate/src/components/TellUs.js#L4)

**Comment by ghost** [comment]
Hi Tauqeer. Can you please clarify what you mean by solving the setup of the `useState` hook?
What would you like to do with the `textarea` tag besides managing its state?

**Comment by TauqeerAhmad5201** [comment]
Hey Imran, though the issue has been resolved recently. We shall be putting up some more issues very soon.

**Comment by ghost** [comment]
No problem. I'll keep an eye out for more issues.
